# Generated by Django 4.0.5 on 2023-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览量')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('likes', models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞量')),
                ('comments', models.PositiveIntegerField(default=0, editable=False, verbose_name='评论数量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('public', models.BooleanField(default=True)),
                ('content', models.TextField(max_length=10000, verbose_name='评论')),
                ('ip_address', models.TextField(default='未知', editable=False, verbose_name='ip地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('public', models.BooleanField(default=True)),
                ('verb', models.CharField(max_length=20, verbose_name='行为')),
                ('content', models.TextField(max_length=10000, verbose_name='内容')),
                ('reply_content', models.TextField(max_length=10000, verbose_name='回复内容')),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='查询内容')),
                ('hot', models.PositiveIntegerField(default=1, editable=False, verbose_name='热度')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='tag')),
                ('hot', models.PositiveIntegerField(default=0, editable=False, verbose_name='热度')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
