# Generated by Django 4.0.5 on 2023-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_privatemessage_privatechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
